import { ThemeInterface } from './contexts/ThemesContext';

const Themes: ThemeInterface[] = [
  {
    id: 1,
    name: 'Basic Theme',
    copy: "#4F46E5",
    disconnect: "#FF0000",
    sender: "#553CEE",
    senderText: "#FFFFFF",
    peer: "#E5E7EB",
    peerText: "#000000",
    headerBackground: "#FAFAFA",
    headerTextColor: "#000000",
    borderColor: '#FFFFFF',
    borderWidth: '0px',
    sendButtonFileName: "/images/send.svg",
    chatBackgroundColor: "#FFFFFF",
    chatBorderRadius: '16px',
    topSectionBottomBorderWidth: '1px',
    typingAreaBackgroundColor: "#FFFFFF",
    typingAreaBottomBorder: '1px solid #E5E7EB',
    typingAreaTopBorder: '',
    inputTextColor: "#000000",
    typingAreaInnerBorderColor: '#6B7280',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '0px',
    backgroundThemeName: 'bg-grid-background',
    systemMessageColor: '#000000'
  },
  {
    id: 2,
    name: 'AOLOL',
    copy: "#0000FF",
    disconnect: "#FF0000",
    sender: "#FF0000",
    senderText: "#000000",
    peer: "#0000FF",
    peerText: "#000000",
    headerBackground: "#ECE9D8",
    headerTextColor: "#000000",
    borderColor: "#015BEE",
    borderWidth: "3px",
    sendButtonFileName: "/images/aolSend.png",
    chatBackgroundColor: "#FFFFFF",
    chatBorderRadius: '0px',
    topSectionBottomBorderWidth: '3px',
    typingAreaBackgroundColor: "#FFFFFF",
    typingAreaBottomBorder: '3px solid #0000FF',
    typingAreaTopBorder: '3px solid #0000FF',
    inputTextColor: "#000000",
    typingAreaInnerBorderColor: '',
    borderTopLeftRadius: '0px',
    borderTopRightRadius: '0px',
    borderBottomLeftRadius: '0px',
    borderBottomRightRadius: '0px',
    backgroundThemeName: 'bg-aolol-background',
    systemMessageColor: '#000000'
  },
  {
    id: 3,
    name: 'Vaporwave',
    copy:"#F2D15D",
    disconnect: "#FF0000",
    sender: "#00E3FF",
    senderText: "#383257",
    peer: "#E100E6",
    peerText: "#FFFFFF",
    headerBackground: "#490F82",
    headerTextColor: "#FFFFFF",
    borderColor: "#CD0CDF",
    borderWidth: "5px",
    sendButtonFileName: "/images/send-vaporwave.svg",
    chatBackgroundColor: "#383257",
    chatBorderRadius: '0px',
    topSectionBottomBorderWidth: '5px',
    typingAreaBackgroundColor: '#322257',
    typingAreaBottomBorder: '5px solid #CD0CDF',
    typingAreaTopBorder: '5px solid #CD0CDF',
    inputTextColor: "#FFFFFF",
    typingAreaInnerBorderColor: '',
    borderTopLeftRadius: '0px',
    borderTopRightRadius: '0px',
    borderBottomLeftRadius: '0px',
    borderBottomRightRadius: '0px',
    backgroundThemeName: 'bg-vaporwave-background',
    systemMessageColor: '#FFFFFF'
  },
  {
    id: 4,
    name: 'Interstellar',
    copy:"#A3C7D6",
    disconnect: "#FF0000",
    sender: "#FF8BFF",
    senderText: "#FFFFFF",
    peer: "#9AC8D8",
    peerText: "#FFFFFF",
    headerBackground: "#3F3B6C",
    headerTextColor: "#FFFFFF",
    borderColor: "#9F73AB",
    borderWidth: "2px",
    sendButtonFileName: "/images/send-interstellar.svg",
    chatBackgroundColor: "#664D86",
    chatBorderRadius: '0px',
    topSectionBottomBorderWidth: '2px',
    typingAreaBackgroundColor: '#3F3B6C',
    typingAreaBottomBorder: '2px solid #9F73AB',
    typingAreaTopBorder: '2px solid #9F73AB',
    inputTextColor: "#FFFFFF",
    typingAreaInnerBorderColor: '',
    borderTopLeftRadius: '0px',
    borderTopRightRadius: '0px',
    borderBottomLeftRadius: '0px',
    borderBottomRightRadius: '0px',
    backgroundThemeName: 'bg-interstellar-background',
    systemMessageColor: '#FFFFFF'
  },
  {
    id: 5,
    name: 'Dim Mode',
    copy: "#FFFFFF",
    disconnect: "#FF0000",
    sender: "#553CEE",
    senderText: "#FFFFFF",
    peer: "#354153",
    peerText: "#FFFFFF",
    headerBackground: "#333333",
    headerTextColor: "#CECECE",
    borderColor: "#000000",
    borderWidth: "0px",
    sendButtonFileName: "/images/send.svg",
    chatBackgroundColor: "#1F1F1F",
    chatBorderRadius: '16px',
    topSectionBottomBorderWidth: '0px',
    typingAreaBackgroundColor: '#333333',
    typingAreaBottomBorder: '1px solid #6B7280',
    typingAreaTopBorder: '',
    inputTextColor: "#FFFFFF",
    typingAreaInnerBorderColor: '#6B7280',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '0px',
    backgroundThemeName: 'bg-dark-grid-background',
    systemMessageColor: '#FFFFFF'
  }
]

export default Themes;
